import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createLiveMatchState, performLiveSub, simulateMatch, tickLiveMatch } from "../src/game/match";
import { applySavedLineup } from "../src/game/club";
import { createRng } from "../src/game/rng";
import { overallFromSkills } from "../src/game/rating";
import { EVENT_CODES } from "../src/game/constants";
import type { Club, Match, MatchSimulationDiagnostics, Player, Position, Tactics } from "../src/game/types";
import { MATCH_SIMULATOR_CONFIG } from "../src/matchSimulatorConfig";

/**
 * Calibration instrumentation: MATCH_SIM_OVERRIDE = "a.b.c=value,d.e.f=value"
 * patches coefficients on the in-memory MATCH_SIMULATOR_CONFIG before simulation,
 * so the engine is tuned without editing match-simulator.jsonc per sweep point.
 * Paths are deep-set on the (unfrozen) exported config object.
 */
function applyOverrides(): void {
  const raw = process.env.MATCH_SIM_OVERRIDE;
  if (!raw) return;
  const m = MATCH_SIMULATOR_CONFIG as Record<string, unknown>;
  for (const part of raw.split(/[;,]/)) {
    const eq = part.indexOf("=");
    if (eq < 0) continue;
    const path = part.slice(0, eq).trim().split(".");
    const value = Number(part.slice(eq + 1).trim());
    if (!Number.isFinite(value)) throw new Error(`MATCH_SIM_OVERRIDE value is not numeric: ${part}`);
    let o: Record<string, unknown> = m;
    for (let i = 0; i < path.length - 1; i++) {
      const next = o[path[i]] as Record<string, unknown> | undefined;
      if (!next) throw new Error(`MATCH_SIM_OVERRIDE path missing: ${part}`);
      o = next;
    }
    if (!(path[path.length - 1] in o)) throw new Error(`MATCH_SIM_OVERRIDE path missing: ${part}`);
    o[path[path.length - 1]] = value;
  }
}

type Sample = { goals: number; shots: number; shotsOnTarget: number; xg: number; corners: number; fouls: number; yellows: number; reds: number; straightReds: number; secondYellowReds: number; passes: number; injuries: number; homePossession: number; homeGoals: number; awayGoals: number; homeXg: number; awayXg: number; homeShots: number; awayShots: number; homeTurnovers: number; awayTurnovers: number; homeCorners: number; awayCorners: number; diagnostics?: MatchSimulationDiagnostics | null };
type Summary = { name: string; count: number; means: Record<string, number>; percentiles: Record<string, [number, number, number]>; result: { home: number; draw: number; away: number }; goalHistogram: Record<number, number> };
const ROOT = dirname(fileURLToPath(import.meta.url));
const REPORT_JSON = join(ROOT, "..", "..", "plans", "match-calibration-report.json");
const SEED = 0x51a7c0de;
const POSITIONS: Position[] = [0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 2, 3, 1, 4];

function club(id: number, tactics: Tactics): Club { return { id, name: id === 1 ? "Calibration Home" : "Calibration Away", shortName: id === 1 ? "H" : "A", ownerUserId: null, timezone: null, competitionState: "ACTIVE", lastMeaningfulActivityAt: null, abandonmentEligibleAt: null, liveMatchAt: null, country: "BRA", highestDivision: 1, cash: 1e8, stadiumName: "Ground", stadiumCapacity: 40000, primaryColor: "#000", secondaryColor: "#fff", coachName: "Coach", tactics, trainingFocus: "assistant", captainId: null, penaltyTakerId: null, savedLineup: null, isHuman: false, ledger: { income: [], expense: [] }, trophies: {} }; }
function makePlayer(id: number, clubId: number, position: Position, strength: number, energy: number): Player { const b = Math.max(1, Math.min(99, strength + (position === 1 ? 1 : position === 4 ? 2 : 0))); const skills = { gol: Math.max(1, Math.min(99, b + (position === 0 ? 5 : -8))), vel: b, tec: b, pas: b + (position === 3 ? 2 : 0), des: b + (position <= 2 ? 3 : -2), arm: b + (position === 2 ? 3 : 0), fin: b + (position === 4 ? 5 : -3) }; return { id, name: `P${id}`, country: "BRA", age: 25, position, side: 0, skills, overall: overallFromSkills(position, skills), potential: 99, tier: 3, energy, salary: 100000, payrollPaidThroughDay: 0, payrollPaidAmount: 0, payrollPeriodStartDay: 0, value: 1e6, releaseClause: 1e6, injuryDays: 0, contractDays: 1000, isYouth: false, starter: false, growthAcc: 0, potentialAcc: 0, skillAcc: [0, 0, 0, 0, 0, 0, 0], careerGoals: 0, careerAssists: 0, seasonGoals: 0, seasonAssists: 0, yellows: 0, reds: 0, clubId, tacPos: -1, onSale: false, suspendedGames: 0, loanId: null, developmentProfile: { declineStartAge: 32, developmentRate: 0, developmentVolatility: 0 }, recentMinutes: [] }; }
function squad(clubId: number, strength: number, energy: number, offset: number): Player[] { return POSITIONS.map((position, i) => makePlayer(offset + i + 1, clubId, position, strength, energy)); }
function tactics(style: number, pressing = 0): Tactics { return { formation: 4, style, pressing, direction: 0 }; }
function clone(players: Player[]): Player[] { return players.map((p) => ({ ...p, skills: { ...p.skills }, skillAcc: [...p.skillAcc], recentMinutes: [...p.recentMinutes], developmentProfile: { ...p.developmentProfile } })); }
function pair(index: number, hs: number, as: number, ht = tactics(0), at = tactics(0), energy = 100, oop = false) { const home = club(1, ht); const away = club(2, at); const hp = squad(1, hs, energy, 1000); const ap = squad(2, as, energy, 2000); if (oop) { const ids = hp.slice(0, 11).map((p) => p.id); [ids[1], ids[2]] = [ids[2], ids[1]]; [ids[3], ids[9]] = [ids[9], ids[3]]; applySavedLineup(home, hp, { formation: 4, starters: ids, subs: hp.slice(11, 23).map((p) => p.id), penaltyTakerId: null, freeKickTakerId: null }); } return { home, away, players: [...hp, ...ap], seed: SEED + index * 7919 }; }
function full(index: number, hs: number, as: number, ht = tactics(0), at = tactics(0), energy = 100, neutral = true, oop = false): Match { const p = pair(index, hs, as, ht, at, energy, oop); return simulateMatch(createRng(p.seed), p.home, p.away, clone(p.players), { competitionId: 1, fixtureId: index, year: 1, homeNeutral: neutral, collectDiagnostics: true }).match; }
function dismissal(index: number, minute: number, substitute: boolean): Match { const p = pair(index, 55, 55); const players = clone(p.players); const rng = createRng(p.seed); const st = createLiveMatchState(rng, p.home, p.away, players, { matchId: index, competitionId: 1, fixtureId: index, homeNeutral: true }); tickLiveMatch(rng, p.home, p.away, players, st, minute, { ignoreHalfTime: true }); const out = st.homeOn[st.homeOn.length - 1]; if (substitute) performLiveSub(rng, p.home, p.away, players, st, 0, out, st.homeSubs[0]); else { st.homeOn = st.homeOn.filter((id) => id !== out); st.homeXI = st.homeXI.filter((id) => id !== out); } tickLiveMatch(rng, p.home, p.away, players, st, 90 - minute, { ignoreHalfTime: true }); return { id: index, fixtureId: index, competitionId: 1, homeClubId: 1, awayClubId: 2, homeScore: st.scores[0], awayScore: st.scores[1], penaltyWinnerId: null, attendance: 0, gateRevenue: 0, events: st.events, stats: st.teamStats, minuteEvents: [], minutes: st.playerMinutes }; }
function sample(m: Match): Sample { const h = m.stats.home, a = m.stats.away, total = h.controlledBallSeconds + a.controlledBallSeconds; const straightReds = m.events.filter((e) => e.type === EVENT_CODES.RED).length; const secondYellowReds = m.events.filter((e) => e.type === EVENT_CODES.YELLOW_RED).length; return { goals: m.homeScore + m.awayScore, shots: h.shots + a.shots, shotsOnTarget: h.shotsOnTarget + a.shotsOnTarget, xg: h.xG + a.xG, corners: h.corners + a.corners, fouls: h.fouls + a.fouls, yellows: h.yellows + a.yellows, reds: h.reds + a.reds, straightReds, secondYellowReds, passes: h.passes + a.passes, injuries: h.injuries + a.injuries, homePossession: total ? h.controlledBallSeconds / total * 100 : 50, homeGoals: m.homeScore, awayGoals: m.awayScore, homeXg: h.xG, awayXg: a.xG, homeShots: h.shots, awayShots: a.shots, homeTurnovers: h.turnovers, awayTurnovers: a.turnovers, homeCorners: h.corners, awayCorners: a.corners, diagnostics: m.simulationDiagnostics ?? null }; }
function percentile(v: number[], p: number): number { const a = [...v].sort((x, y) => x - y), i = (a.length - 1) * p, l = Math.floor(i), h = Math.ceil(i); return a.length ? a[l] + (a[h] - a[l]) * (i - l) : 0; }
function summarize(name: string, values: Sample[]): Summary { const keys = ["goals", "shots", "shotsOnTarget", "xg", "corners", "fouls", "yellows", "reds", "straightReds", "secondYellowReds", "passes", "injuries", "homePossession", "homeXg", "awayXg", "homeShots", "awayShots", "homeTurnovers", "awayTurnovers", "homeCorners", "awayCorners"] as const; if (!values.length) throw new Error(`${name}: cannot summarize zero samples`); const means: Record<string, number> = {}, ps: Record<string, [number, number, number]> = {}; for (const k of keys) { const v = values.map((x) => x[k]); means[k] = v.reduce((s, x) => s + x, 0) / values.length; ps[k] = [percentile(v, .05), percentile(v, .5), percentile(v, .95)]; } const result = { home: 0, draw: 0, away: 0 }, goalHistogram: Record<number, number> = {}; for (const x of values) { if (x.homeGoals > x.awayGoals) result.home++; else if (x.homeGoals < x.awayGoals) result.away++; else result.draw++; goalHistogram[x.goals] = (goalHistogram[x.goals] ?? 0) + 1; } const summary = { name, count: values.length, means, percentiles: ps, result: { home: result.home / values.length, draw: result.draw / values.length, away: result.away / values.length }, goalHistogram }; if (Math.abs(summary.result.home + summary.result.draw + summary.result.away - 1) > 1e-9) throw new Error(`${name}: H/D/A does not sum to 100%`); return summary; }
const styles: Record<string, number> = { CONTROL: 0, PRESS: 1, COUNTER: 2 };
function run(name: string, i: number): Match { if (name === "neutral-baseline") return full(i, 55, 55); if (name === "identical-home-away") return full(i, 55, 55, tactics(0), tactics(0), 100, false); if (name === "P10-vs-P50-neutral") return full(i, 42, 55); if (name === "P25-vs-P50-neutral") return full(i, 49, 55); if (name === "P50-vs-P50-neutral") return full(i, 55, 55); if (name === "P75-vs-P50-neutral") return full(i, 61, 55); if (name === "P90-vs-P50-neutral") return full(i, 68, 55); if (name === "P10-vs-P90-neutral") return full(i, 42, 68); if (name === "P90-vs-P10-neutral") return full(i, 68, 42); if (name.startsWith("tactics-")) { const [, h, , a] = name.split("-"); return full(i, 55, 55, tactics(styles[h], styles[h] === 1 ? 2 : 0), tactics(styles[a], styles[a] === 1 ? 2 : 0)); } if (name.startsWith("energy-")) return full(i, 55, 55, tactics(0), tactics(0), Number(name.slice(7))); if (name === "out-of-position") return full(i, 55, 55, tactics(0), tactics(0), 100, true, true); if (name === "minute-60-substitution") return dismissal(i, 60, true); if (name.startsWith("10v11-minute-")) return dismissal(i, Number(name.slice(13)), false); throw new Error(`Unknown scenario ${name}`); }
const ALL = ["neutral-baseline", "P10-vs-P50-neutral", "P25-vs-P50-neutral", "P50-vs-P50-neutral", "P75-vs-P50-neutral", "P90-vs-P50-neutral", "P10-vs-P90-neutral", "P90-vs-P10-neutral", "identical-home-away", ...["CONTROL", "PRESS", "COUNTER"].flatMap((h) => ["CONTROL", "PRESS", "COUNTER"].map((a) => `tactics-${h}-vs-${a}`)), "energy-100", "energy-75", "energy-50", "10v11-minute-30", "10v11-minute-60", "out-of-position", "minute-60-substitution"];
function snapshot(): Record<string, unknown> { const m = MATCH_SIMULATOR_CONFIG as Record<string, any>; return { influence: { team: .4, tactics: .35, luck: .25 }, foulMultiplier: m.probabilityModel.foulProbabilityCalibrationMultiplier, shotOnTarget: m.shotModel.shotsOnTarget, homeAdvantage: m.homeAdvantage, normalization: m.normalization, cards: m.cards, injuries: m.injuries, timing: { tempoScale: m.timing.tempoScale, regulationSeconds: m.timing.regulationSeconds }, tacticalActionMix: m.tacticalActionMix, xgGlobal: m.shotModel.xgLookup.GLOBAL.GLOBAL }; }
function main(): void { applyOverrides(); const name = process.env.MATCH_SIM_ONLY ?? "neutral-baseline"; const count = name === "neutral-baseline" ? Number(process.env.MATCH_SIM_BASELINE_COUNT ?? 20000) : Number(process.env.MATCH_SIM_COUNT ?? 5000); if (!Number.isInteger(count) || count <= 0) throw new Error(`invalid simulation count: ${count}`); const start = Number(process.env.MATCH_SIM_START ?? 0); const names = name === "all" ? ALL : [name]; const raw: Record<string, Sample[]> = {}; const results: Summary[] = []; for (const n of names) { raw[n] = []; const total = n === "neutral-baseline" ? count : Number(process.env.MATCH_SIM_COUNT ?? 5000); for (let i = 0; i < total; i++) raw[n].push(sample(run(n, start + i))); results.push(summarize(n, raw[n])); } const out = { seed: SEED, config: snapshot(), results, raw }; const output = process.env.MATCH_SIM_OUTPUT ?? REPORT_JSON; mkdirSync(dirname(output), { recursive: true }); writeFileSync(output, JSON.stringify(out, null, 2)); process.stdout.write(JSON.stringify(results)); }
function markdown(results: Summary[], config: Record<string, unknown>): string { const b = results.find((x) => x.name === "neutral-baseline"), h = results.find((x) => x.name === "identical-home-away"), c = config as any; const targets: Record<string, string> = { goals: "2.4-3.0", shots: "22-27", shotsOnTarget: "7.5-10", xg: "2.3-2.8", corners: "8.5-11.5", fouls: "22-31", yellows: "3.5-4.7", reds: "0.04-0.10", passes: "900-1050", injuries: "0.5-0.8" }; const l = ["# Match Simulator Calibration", "", "Deterministic seeded Monte Carlo against the production possession engine. No outcomes are scripted.", "", "## Config Changes", "", "| Coefficient | Before | After |", "|---|---:|---:|"]; l.push(`| influence team/tactics/luck | 0.40 / 0.35 / 0.25 | 0.40 / 0.35 / 0.25 |`, `| foul multiplier | 1.9446934276508636 | ${c.foulMultiplier} |`, `| shot on-target base rate | 0.3473620650615141 | ${c.shotOnTarget.baseRate} |`, `| home target xG | 0.25 | ${c.homeAdvantage.targetXg} |`, `| yellow / red targets | 4.5 / 0.15 | ${c.cards.yellowTargetPerMatch} / ${c.cards.redTargetPerMatch} |`, `| injury target | 0.35 | ${c.injuries.targetPerMatch} |`, "", "## Neutral Benchmark", "", "| Metric | Mean | P05 / P50 / P95 | Target |", "|---|---:|---:|---|"); for (const k of Object.keys(targets)) l.push(`| ${k} | ${b?.means[k]?.toFixed(3)} | ${b?.percentiles[k]?.map((x) => x.toFixed(3)).join(" / ")} | ${targets[k]} |`); if (h) l.push("", "## Home Advantage", "", `Identical teams H/D/A ${(h.result.home * 100).toFixed(1)}% / ${(h.result.draw * 100).toFixed(1)}% / ${(h.result.away * 100).toFixed(1)}%; xG ${h.means.homeXg.toFixed(3)} / ${h.means.awayXg.toFixed(3)} (difference ${(h.means.homeXg - h.means.awayXg).toFixed(3)}).`); l.push("", "## Scenario Results", "", "| Scenario | N | Goals | Shots | xG | Possession | H/D/A |", "|---|---:|---:|---:|---:|---:|---:|"); for (const x of results) l.push(`| ${x.name} | ${x.count} | ${x.means.goals.toFixed(3)} | ${x.means.shots.toFixed(3)} | ${x.means.xg.toFixed(3)} | ${x.means.homePossession.toFixed(2)}% | ${(x.result.home * 100).toFixed(1)} / ${(x.result.draw * 100).toFixed(1)} / ${(x.result.away * 100).toFixed(1)}% |`); l.push("", "## Notes", "", "Strength rows provide the monotonicity check; tactics are evaluated through possession, turnovers, shots and cards. Goal histograms and full percentile distributions are in the JSON sidecar. The engine's second-yellow rule makes the requested yellow and red ranges incompatible; the red range is prioritized and any yellow shortfall is reported.", ""); return l.join("\n"); }
main();
