import type { Club, World } from "../game/types";
import { createRng } from "../game/rng";
import { nextInt } from "../game/rng";
import { tacticsForClub, divisionTicketTier } from "../game/club";
import { STARTING_CASH, TICKET_PRICES } from "../game/constants";
import { generateName } from "../game/names";
import { MP_CONFIG } from "../config";
import { generateNewClubRoster, totalDivisionsForGeneration } from "./clubGenerator";

/**
 * World generation for the multiplayer game. The world is a single shared
 * object persisted in one global Save row; the pyramid is built by the
 * multiplayer engine (see game/multiplayer.ts) rather than here.
 */
export function generateWorld(seed: number): World {
  const rng = createRng(seed);
  return {
    seed,
    year: 1,
    dayIndex: 0,
    dayOfWeek: 0,
    nextId: 1,
    clubs: [],
    players: [],
    competitions: [],
    fixtures: [],
    matches: [],
    news: [{ dayIndex: 0, text: "Welcome to Footmania! A new season is about to begin.", kind: "season" }],
    loans: [],
    marketBids: [],
    transferAuctions: [],
    freeAgentListings: [],
    marketReservations: [],
    playerMarketHistory: [],
    aiEvaluations: [],
    seasonAwards: [],
    records: [],
    managerHistory: [],
    ticketPrices: {},
    stadiumUpgrades: [],
    humanClubId: null,
    seasonSummary: null,
    rng,
    contractWarnings: [],
    financialInterventions: [],
    mp: {
      seasonId: 0,
      seasonYear: 1,
      seasonMonth: 1,
      seasonStatus: "PREPARATION",
      completedRounds: 0,
      joinLockRound: Math.floor(MP_CONFIG.joinThresholdPercent * 14),
      joinState: "OPEN",
      joinThresholdPercent: MP_CONFIG.joinThresholdPercent,
      inactivityThresholds: { ...MP_CONFIG.inactivityThresholds },
      matchTimeMode: MP_CONFIG.matchTimeMode,
      matchKickoffHour: MP_CONFIG.matchKickoffHourUtc,
      lastProcessedGameDay: 0,
      lastDailyTickDay: 0,
      lastDailyTickDate: null,
      manualRound: null,
      rolloverPhase: null,
      absoluteGameDay: 0,
      seasonNumber: 1,
      seasonDayIndex: 0,
      phase: "ACTIVE",
      lastAdvancedAt: null,
      clockVersion: 0,
      startAbsoluteGameDay: 0,
      seasonStartAt: null,
      rolloverContext: null,
      calendarMigrationVersion: 1,
      loanEndAbsoluteGameDays: {},
      stadiumCompletionAbsoluteGameDays: {},
    },
    mpQueue: [],
    liveMatches: [],
    seasonAllocations: [],
    mpMemberships: [],
    mpClubSeasons: [],
    mpActivities: [],
    mpAudits: [],
    seasonHistory: [],
    generationEvents: [],
  };
}

export interface HumanClubOptions {
  userId: number;
  clubName: string;
  country: string;
  timezone: string | null;
  primaryColor?: string;
  secondaryColor?: string;
  stadiumName?: string;
}

/**
 * Creates a brand-new persistent human club. The club is independent of any
 * AI slot it may later replace (plan §8): identity, roster, finances and
 * facilities all belong to the human club record.
 */
export function createHumanClub(world: World, opts: HumanClubOptions): Club {
  const rng = world.rng;
  const id = world.nextId++;
  const name = opts.clubName.trim();
  const stadiumName = opts.stadiumName?.trim() || `${name} Stadium`;
  const initialDivision = totalDivisionsForGeneration(world);
  const club: Club = {
    id,
    name,
    shortName: name,
    ownerUserId: opts.userId,
    timezone: opts.timezone,
    competitionState: "NEW",
    lastMeaningfulActivityAt: Date.now(),
    abandonmentEligibleAt: null,
    inactivityWarningStage: 0,
    liveMatchAt: null,
    country: opts.country,
    // The initial roster uses the current bottom edge; actual first placement
    // can replace this provisional value when the club enters competition.
    highestDivision: initialDivision,
    cash: STARTING_CASH[2], // Division 1 new-club starting cash
    stadiumName,
    // Neutral default; stadium/capacity logic is slated for a separate revamp.
    stadiumCapacity: Math.max(15000, Math.min(60000, 15 * 1100 + nextInt(rng, 15000))),
    primaryColor: opts.primaryColor ?? "#d40000",
    secondaryColor: opts.secondaryColor ?? "#ffffff",
    coachName: generateName(rng, opts.country),
    tactics: tacticsForClub(rng),
    trainingFocus: "assistant",
    captainId: null,
    penaltyTakerId: null,
    isHuman: true,
    ledger: { income: [], expense: [] },
    trophies: {},
  };
  world.clubs.push(club);
  const base = TICKET_PRICES[divisionTicketTier(1)].map((x) => Math.max(1, Math.round(x / 200))) as [number, number, number, number];
  world.ticketPrices[club.id] = base;
  // The human club's initial roster is generated by the canonical division-driven
  // generator. A brand-new human club has no division until placement, so the
  // senior squad starts at the bottom division's expectation (player-generation
  // §72); placement / first rollover records the real division for future intake.
  generateNewClubRoster({
    world,
    club,
    currentDivision: initialDivision,
    highestDivisionReached: initialDivision,
    totalDivisions: initialDivision,
    seasonId: null,
  });
  return club;
}
