import { createRng } from "../src/game/rng";
import type { Club, Player, World } from "../src/game/types";

export function makeClub(overrides: Partial<Club> = {}): Club {
  return {
    id: 1,
    name: "Test FC",
    shortName: "TFC",
    ownerUserId: 1,
    timezone: null,
    competitionState: "ACTIVE",
    lastMeaningfulActivityAt: null,
    abandonmentEligibleAt: null,
    liveMatchAt: null,
    country: "BRA",
    level: 20,
    cash: 100_000_000,
    stadiumName: "St",
    stadiumCapacity: 40000,
    primaryColor: "#000",
    secondaryColor: "#fff",
    coachName: "Coach",
    boardConfidence: 50,
    fanConfidence: 70,
    tactics: { formation: 4, style: 0, pressing: 0, direction: 0 },
    trainingFocus: "assistant",
    captainId: null,
    penaltyTakerId: null,
    isHuman: true,
    ledger: { income: [], expense: [] },
    trophies: {},
    ...overrides,
  };
}

export function makeWorld(clubs: Club[], players: Player[], overrides: Partial<World> = {}): World {
  return {
    seed: 1,
    year: 2026,
    dayIndex: 0,
    dayOfWeek: 0,
    nextId: 1000,
    clubs,
    players,
    competitions: [],
    fixtures: [],
    matches: [],
    news: [],
    auctions: [],
    loans: [],
    seasonAwards: [],
    records: [],
    managerHistory: [],
    ticketPrices: {},
    stadiumUpgrades: [],
    tvDeals: [],
    humanClubId: clubs[0]?.id ?? null,
    seasonSummary: null,
    rng: createRng(42),
    contractWarnings: [],
    mp: {
      seasonId: 1,
      seasonYear: 2026,
      seasonMonth: 1,
      seasonStatus: "ACTIVE",
      completedRounds: 0,
      joinLockRound: 7,
      joinState: "OPEN",
      joinThresholdPercent: 0.5,
      inactivityThresholds: { 1: 42, 2: 35, default: 28 },
      matchTimeMode: "GLOBAL_FIXED_KICKOFF",
      matchKickoffHour: 20,
      lastProcessedGameDay: 0,
      lastDailyTickDay: 0,
      lastDailyTickDate: null,
      manualRound: null,
      rolloverPhase: null,
    },
    mpQueue: [],
    liveMatches: [],
    seasonAllocations: [],
    mpMemberships: [],
    mpClubSeasons: [],
    mpActivities: [],
    mpAudits: [],
    seasonHistory: [],
    ...overrides,
  };
}
