export const strings = {
  app: {
    name: "Footmania",
    tagline: "Take charge of your club",
  },
  auth: {
    login: "Sign In",
    register: "Create Account",
    username: "Username",
    password: "Password",
    confirmPassword: "Confirm Password",
    usernameHint: "3-24 characters, letters/numbers/underscore",
    passwordHint: "At least 6 characters",
    noAccount: "New manager?",
    hasAccount: "Already a manager?",
    logout: "Sign out",
  },
  saves: {
    title: "My Saves",
    newSave: "New Save",
    continue: "Continue",
    delete: "Delete",
    name: "Save Name",
    startNew: "New Career",
    createTeam: "Create Your Team",
    createTeamHint: "Pick the country of your club. Your players, academy and coach will come from this country's name pool.",
    teamName: "Team Name",
    teamNamePlaceholder: "Team name (coming in multiplayer)",
    colors: "Colors",
    colorsPlaceholder: "Club colors (coming in multiplayer)",
    stadium: "Stadium",
    stadiumPlaceholder: "Stadium name (coming in multiplayer)",
    multiplayerHint: "Name, colors and stadium customization arrive with multiplayer.",
    country: "Country",
    noSaves: "No saves yet. Start a new career to become a manager.",
    date: "Date",
  },
  dashboard: {
    title: "Dashboard",
    continue: "Continue",
    resume: "Resume match",
    liveMatch: "Live match",
    liveMatchHint: "A match is being played right now. Resume it to keep watching.",
    nextFixture: "Next Match",
    noNextFixture: "No upcoming matches",
    cash: "Cash",
    board: "Board",
    fans: "Fans",
    news: "News",
    position: "League Position",
    seasonEnded: "Season Complete",
    seasonEndedMsg: "The season is over. Start a new year.",
  },
  team: {
    country: "Country",
  },
  nav: {
    home: "Home",
    squad: "Squad",
    tables: "Tables",
    matches: "Matches",
    transfers: "Transfers",
    finances: "Finances",
  },
  squad: {
    title: "Squad",
    seniors: "Senior Squad",
    juniors: "Youth Squad",
    tactics: "Tactics",
    formation: "Formation",
    style: "Style",
    pressing: "Pressing",
    direction: "Direction",
    overall: "OVR",
    potential: "POT",
    value: "Value",
    salary: "Salary",
    contract: "Contract",
    energy: "Energy",
    age: "Age",
    position: "Pos",
    player: "Player",
    renew: "Renew Contract",
    contractMonths: "Length (seasons)",
    newSalary: "New Salary",
    contractDone: "Contract renewed",
    trainingFocus: "Training focus",
    trainingAssistant: "Assistant",
    trainingPrimary: "Primary",
    trainingSecondary: "Secondary",
    trainingHint: "Training focus is applied automatically every game day.",
    overallHint: "Overall is calculated from position-specific skills; individual skills drive match performance.",
    characteristic: "Traits",
    promoteYouth: "Promote to senior squad",
    dismissYouth: "Release from academy",
    release: "Release",
    releaseConfirm: "Release {{name}}? Paying the release clause will make the player a free agent.",
    releaseDone: "Player released",
  },
  competitions: {
    title: "Competitions",
    table: "Table",
    fixtures: "Fixtures",
    bracket: "Bracket",
    round: "Round",
    leg: "Leg",
    group: "Group",
    finished: "Finished",
    knockoutTable: "This is a knockout competition — see the Bracket tab",
  },
  transfers: {
    title: "Transfers",
    sell: "List for Sale",
    auction: "Auction",
    fixedPrice: "Fixed Price",
    bid: "Make Bid",
    yourBid: "Your bid",
    counterOffer: "Counter-offer",
    auctions: "Auctions",
    freeAgents: "Free Agents",
    sign: "Sign",
    loan: "Take on loan",
    borrowLoanHint: "Add squad depth without paying a transfer or signing fee; your club pays the salary during the loan.",
    lendLoanHint: "Keep ownership while the receiving club pays the salary and regular playing time helps the player develop.",
    bidAccepted: "Bid accepted!",
    bidRejected: "Bid rejected",
    price: "Price",
    forSale: "For Sale",
  },
  finances: {
    title: "Finances",
    income: "Income",
    expense: "Expenses",
    balance: "Balance",
  },
  matchday: {
    title: "Match Day",
    results: "Results",
    live: "Watch Live",
    home: "Home",
    away: "Away",
    minute: "min",
    possession: "Possession",
    shots: "Shots",
    onGoal: "On Target",
    fouls: "Fouls",
    finish: "Finish",
    fullTime: "Full Time",
  },
  seasonEnd: {
    title: "Season Review",
    champion: "Champion",
    runnerUp: "Runner-up",
    newYear: "Start New Season",
  },
  common: {
    loading: "Loading...",
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    confirm: "Confirm",
    back: "Back",
    error: "Something went wrong",
  },
  settings: {
    matchDurationTitle: "Human match duration",
    matchDurationHint: "How long (in real time) a match you play should last. AI-vs-AI matches always resolve instantly with the same engine.",
    matchDuration: "Match duration",
    matchDurationPreview: "Estimated",
    saved: "Saved",
  },
};
