export const strings = {
  app: {
    name: "Footmania",
    tagline: "Take charge of your club",
  },
  auth: {
    logout: "Sign out",
  },
  join: {
    title: "Create Your Club",
    startNew: "Join the World",
    teamName: "Team Name",
    stadium: "Stadium",
    country: "Country",
  },
  dashboard: {
    title: "Dashboard",
    continue: "Continue",
    goToMatch: "Go to match",
    liveMatch: "Live match",
    liveMatchHint: "Watch the action live and make substitutions.",
    pregame: "Pre-game prep",
    pregameBannerTitle: "Pre-game prep is open",
    pregameBannerHint: "Set your lineup and tactics before kick-off.",
    goToPregame: "Open pre-game prep",
    nextFixture: "Next Match",
    noNextFixture: "No upcoming matches",
    cash: "Cash",
    news: "News",
    position: "League Position",
    seasonEnded: "Season Complete",
    seasonEndedMsg: "The season is over. Start a new year.",
  },
  team: {
    country: "Country",
  },
  nav: {
    home: "Home",
    squad: "Squad",
    tables: "Tables",
    matches: "Matches",
    transfers: "Transfers",
    finances: "Finances",
  },
  squad: {
    title: "Squad",
    seniors: "Senior Squad",
    juniors: "Youth Squad",
    tactics: "Tactics",
    formation: "Formation",
    style: "Style",
    pressing: "Pressing",
    direction: "Direction",
    overall: "OVR",
    value: "Value",
    salary: "Salary",
    contract: "Contract",
    energy: "Energy",
    condition: "Cond",
    injuryCause: "Cause",
    injuredReturn: "Expected return: season day {{day}}",
    age: "Age",
    position: "Pos",
    player: "Player",
    renew: "Renew Contract",
    contractAdditionalSeasons: "Additional seasons after current",
    newSalary: "New Salary",
    contractDone: "Contract renewed",
    trainingFocus: "Training focus",
    automationTitle: "Match Automation",
    trainingAssistant: "Assistant",
    trainingPrimary: "Primary",
    trainingSecondary: "Secondary",
    trainingHint: "Training focus is applied automatically every game day.",
    promoteYouth: "Promote to senior squad",
    dismissYouth: "Release from academy",
    release: "Release",
    releaseConfirm: "Release {{name}}? Paying the release clause will make the player a free agent.",
    releaseDone: "Player released",
  },
  competitions: {
    title: "Tables",
    table: "Standings",
    fixtures: "Fixtures",
    bracket: "Bracket",
    round: "Round",
    leg: "Leg",
    group: "Group",
    finished: "Finished",
    knockoutTable: "This is a knockout competition — see the Bracket tab",
  },
  transfers: {
    title: "Transfers",
    sell: "List for Sale",
    auction: "Auction",
    bid: "Make Bid",
    yourBid: "Your bid",
    auctions: "Auctions",
    freeAgents: "Free Agents",
    sign: "Sign",
    loan: "Take on loan",
    borrowLoanHint: "Add squad depth without paying a transfer or signing fee; your club pays the salary during the loan.",
    lendLoanHint: "Keep ownership while the receiving club pays the salary and regular playing time helps the player develop.",
    forSale: "For Sale",
  },
  finances: {
    title: "Finances",
    income: "Income",
    expense: "Expenses",
    balance: "Balance",
  },
  matchday: {
    title: "Match Day",
    results: "Results",
    live: "Watch Live",
    home: "Home",
    away: "Away",
    minute: "min",
    possession: "Possession",
    shots: "Shots",
    onGoal: "On Target",
    fouls: "Fouls",
    finish: "Finish",
    fullTime: "Full Time",
  },
  seasonEnd: {
    title: "Season Review",
    champion: "Champion",
    runnerUp: "Runner-up",
    newYear: "Start New Season",
  },
  common: {
    loading: "Loading...",
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    confirm: "Confirm",
    back: "Back",
    error: "Something went wrong",
  },
  settings: {
    saved: "Saved",
  },
};
